### PR TITLE
some changes while using this Debian

### PR DESCRIPTION
**Pull request by ana**
GitHub didn't leave me to cherry-pick which commits I wanted to add in the pull request.
Probably the three first commits are the only interesting for you. In any case a029117 is to ignore since it's a change for my internal workflow.

### CODE REVIEW

**Comment by bmiklautz** [comment]
@ana nice! thank you. Regarding a029117 I got some changes not yet pushed.

**Comment by bmiklautz** [comment]
Picked/merged manually to master.
Thx.

**Comment by bmiklautz** [comment]
@ana I've had a problem where I needed the original release number as well have a look to c9b9dee49e1d55f923aa18c6700490ff45d73048

**Comment by ana** [comment]
Thank you!

**Pull request closed without merging**
